---
layout: post
title: 例外処理を考える（１）
date: 2010-09-15 23:07:01.000000000 -05:00
type: post
published: true
status: publish
categories:
- Program
- 例外処理を考える
tags:
- Exception
- Java
meta:
  _edit_last: '1'
  _revision-control: a:1:{i:0;s:8:"defaults";}
  _aioseop_description: プログラマにとって例外処理は避けて通れない厄介な問題です。突然ですが、今回はJavaでの例外処理について考えてみたいと思います。
  _jetpack_related_posts_cache: a:1:{s:32:"1b5750fe692143898c8244009847a17d";a:2:{s:7:"expires";i:1501266989;s:7:"payload";a:3:{i:0;a:1:{s:2:"id";i:199;}i:1;a:1:{s:2:"id";i:899;}i:2;a:1:{s:2:"id";i:931;}}}}
author:
  login: akirakoyasu
  email: mail@akirakoyasu.net
  display_name: Akira Koyasu
  first_name: ''
  last_name: ''
---
<p>プログラマにとって例外処理は避けて通れない厄介な問題です。今回はJavaでの例外処理について考えてみたいと思います。</p>
<p>はじめに、Javaの例外処理のための仕組みを整理しましょう。</p>
<h3>try〜catch〜finally節</h3>
<p>例外を発生させるコード（メソッド・コンストラクタ・もしくは自分で発生させる）を使う部分をtry節で括り、その例外への対処をcatch節に、例外の有無に関わらず行う処理をfinally節に書きます。</p>
<pre>try {

    // 例外を発生させるコード

} catch (SomeException1 e) {

    // SomeException1が発生した場合の処理

} catch (SomeException2 e) {

    // SomeException2が発生した場合の処理

} finally {

    // 例外の有無に関わらず行う処理

}</pre>
<p>異なる例外を処理するcatch節は複数並べて書くことができますが、発生した例外に対応するcatch節かどうかは上から順に判定されることになっているため、ある例外を処理するcatch節の次にそのサブクラスに当たる例外を処理するcatch節を書くことはできません。（到達不能コードとなります）</p>
<p>この複数書ける、というところが重要です。つまり対処する例外とその対処方法を選択できるということですね。<!--more--></p>
<h3>throws句</h3>
<p>メソッドまたはコンストラクタが発生させる（投げる・スローするという）例外を宣言します。</p>
<p>メソッドまたはコンストラクタが例外をスローする可能性がある場合、その例外、もしくはそのスーパークラスである例外をすべて宣言する必要があります。ただし、チェックされない例外（後述）は宣言しなくても構いません。</p>
<h3>throw句</h3>
<p>自分で例外をスローするときに使います。Throwableクラス（Exceptionクラスのスーパークラス）のサブクラスであればスローすることができます。</p>
<h3>例外クラス</h3>
<p>例外そのものを表すクラスです。例外にはチェックされる例外とチェックされない例外があります。</p>
<dl>
<dt>チェックされる例外</dt>
<dd>RuntimeExceptionクラスのサブクラスでない例外</dd>
<dd>チェックされる例外をスローするコードを使う場合、try〜catch節で括って処理するか、外側のメソッドでthrows宣言しなければならない。</dd>
<dt>チェックされない例外</dt>
<dd>RuntimeExceptionクラスのサブクラスである例外</dd>
<dd>チェックされない例外をスローするコードを使う場合は、try〜catch節で括る必要はなく、throws宣言も必要ない。したがって、チェックされない例外の発生は必ずしも予測できない。</dd>
</dl>
<p>端的に言えば、チェックされる例外とは「なんらかの対処をしないとコンパイルできない例外」で、チェックされない例外とは「対処しなくてもコンパイルできる例外」です。</p>
<p>ここに重要なポイントがあります。</p>
<p>つまり<strong>チェックされる例外は、なんらかの対処をすべき・あるいは回復可能な余地があるかもしれない例外</strong>を表し、<strong>チェックされない例外は、対処する意味が無い・もしくは回復不可能な例外</strong>を表すということなのです。（少なくともそういう意図を持って言語設計されています）</p>
<h3>assert句</h3>
<p>アサーション／表明は例外処理機構そのものではありませんが、安全で見やすいコードを書くために役立ちます。</p>
<p>assertに続けて条件式と必要であればメッセージを書きます。実行時にアサーションが有効であり、かつ条件式が偽であればAssertionErrorが発生します。</p>
<p>ちなみにAssertionErrorはThrowableのサブクラスであるため、自分でスローすることもできます。</p>
<blockquote><p>AssertionError &lt;- Error &lt;- Throwable</p></blockquote>
<h3>次回へ</h3>
<p>まずは例外処理のための仕組みをまとめました。次回から具体的な方針について見ていきたいと思います。</p>
